<div id="container"></div>
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
<script>
var gitment = new Gitment({
  owner: 'nagato1208',
  repo: 'nagato1208.github.io',
  oauth: {
    client_id: '60d19c0c9d847e353658',
    client_secret: '338814f8681c6c1c6151f82e093b595cc21e0f4c',
  },
})
gitment.render('container')
</script>
